export const GET_PLAYERS = 'GET_PLAYERS';
export const GET_SETTINGS = 'GET_SETTINGS';
export const SET_NUMBER_PLAYERS = 'SET_NUMBER_PLAYERS';
export const GET_MATCHUPS = 'GET_MATCHUPS';
export const GET_ROUND_MATCHUPS = 'GET_ROUND_MATCHUPS';
export const TOAST_DASH_MESSAGE = 'TOAST_DASH_MESSAGE';
export const TOAST_DASH_CLEAR = 'TOAST_DASH_CLEAR';
